---
title: "Creating a New Python Repo Using this Template"
author: "Jeremy Mikecz"
date: "2026-01-07"
format: html
editor: visual
---

## Create a new repository in Github

## Clone repository on your local computer

## Setup a Virtual Environment using `uv`

There are four main ways you will most commonly set up a virtual environment using `uv` for your project.

1.  install all listed dependencies from a `uv.lock` file included with a repo that you have downloaded or cloned.

2.  install all listed dependencies from a `requirements.txt` file included with a repo that you have downloaded or cloned. For a long time, it was convention in Python to store package dependency information in this file using packages like `venv`. However, you can activate and use such an environment using `uv`.

3.  Create a new project / repository in Github from scratch and initiate a new `uv` environment.

4.  Create a new project locally and initiate `git` and `uv` for this project.

Instructions for options #1 and #2 are below.

Instructions for option #3 and #4 may be found in the [Creating New Repo from Scratch](creating-new-repo_from-scratch.qmd) document.

### Option 1: Install dependencies from existing uv project

1.  Ensure `uv` is already installed. Run `uv`, `uv run main.py`, or `uv --version` in the command line to confirm.
2.  

### Option 2: Install dependencies from existing requirements.txt

## Make changes and add, commit, and push to remote (online) repo

# 

#