---
title: "Creating a New Python Repo Using this Template"
author: "Jeremy Mikecz"
date: "2026-01-07"
format: html
editor: visual
---

## Create a new repository in Github

## Clone (mostly) empty repository on your local computer

## Setup a Virtual Environment using `uv`

There are four main ways you will most commonly set up a virtual environment using `uv` for your project.

1.  install all listed dependencies from a `uv.lock` file included with a repo that you have downloaded or cloned.

2.  install all listed dependencies from a `requirements.txt` file included with a repo that you have downloaded or cloned. For a long time, it was convention in Python to store package dependency information in this file using packages like `venv`. However, you can activate and use such an environment using `uv`.

3.  Create a new project / repository in Github from scratch and initiate a new `uv` environment.

4.  Create a new project locally and initiate `git` and `uv` for this project.

Instructions for options #3 and #4 are below.

Instructions for option #1 and #2 may be found in the [Creating New Repo from Template](creating-new-repo_from-template.qmd) document.

For more information, review the [uv guide to working on projects](https://docs.astral.sh/uv/guides/projects/).

### Option 3: Create a new project in Github, then initiate it with `uv` locally

1.  Install **uv**

2.  Check to see **uv** is available by entering `uv` in the terminal

3.  Create a new python project with `uv init`. Note: in the project's root directory you should now a `.venv` folder and the following files:

    1.  "main.py"
    2.  "pyproject.toml" - contains metadata about your project
    3.  ".python-version" - contains project's default Python version
    4.  It will also create a "README.md" and a ".gitignore" file if not already created.

4.  run the main.py file with `uv run main.py`.

5.  Practice adding a Python package or library to your project environment:

    ```{bash}
    uv add requests
    ```

6.  Update your lockfile (`uv.lock`, which was created when we initiated the uv project environment with `uv init`) by running `uv lock` in the command line (note: if you open the `uv.lock` file you will now see the "requests" package listed (warning: don't edit the uv.lock file directly, instead it will be automatically updated when you add or change packages using `uv` commands.

### Option 4: Create a new project locally and initiate `git` and `uv` before pushing to Github.